# Generated by Django 2.1.7 on 2019-03-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='key_1',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='key_2',
            field=models.BooleanField(null=True),
        ),
    ]
